export const stamps = [
  {
    id: 1,
    catalogNumber: 123,
    typeOfCollection: 'België',
    year: 1985,
    postFreshCatalogPrice: 0.5,
    postFreshSalesPrice: 0.2,
    hingeCatalogPrice: 0.3,
    hingeSalesPrice: 0.15,
    stampedCatalogPrice: 0.25,
    stampedSalesPrice: 0.1,
    onLetterCatalogPrice: 0.1,
    onLetterSalesPrice: 0.05,
  },
  {
    id: 2,
    catalogNumber: 123,
    typeOfCollection: 'België',
    year: 1985,
    postFreshCatalogPrice: 0.5,
    postFreshSalesPrice: 0.2,
    hingeCatalogPrice: 0.3,
    hingeSalesPrice: 0.15,
    stampedCatalogPrice: 0.25,
    stampedSalesPrice: 0.1,
    onLetterCatalogPrice: 0.1,
    onLetterSalesPrice: 0.05,
  },
  {
    id: 3,
    catalogNumber: 123,
    typeOfCollection: 'België',
    year: 1985,
    postFreshCatalogPrice: 0.5,
    postFreshSalesPrice: 0.2,
    hingeCatalogPrice: 0.3,
    hingeSalesPrice: 0.15,
    stampedCatalogPrice: 0.25,
    stampedSalesPrice: 0.1,
    onLetterCatalogPrice: 0.1,
    onLetterSalesPrice: 0.05,
  },
  {
    id: 4,
    catalogNumber: 123,
    typeOfCollection: 'België',
    year: 1985,
    postFreshCatalogPrice: 0.5,
    postFreshSalesPrice: 0.2,
    hingeCatalogPrice: 0.3,
    hingeSalesPrice: 0.15,
    stampedCatalogPrice: 0.25,
    stampedSalesPrice: 0.1,
    onLetterCatalogPrice: 0.1,
    onLetterSalesPrice: 0.05,
  },
];
